name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: erlang:25.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          curl -fsSL https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && mv rebar3 /usr/local/bin/
          rebar3 update

      - name: Run Tests
        run: rebar3 eunit

      - name: Install Erlang and Dialyzer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:erlang/erlang
          sudo apt-get update
          sudo apt-get install -y erlang
          sudo apt-get install -y erlang-dialyzer

      - name: Build PLT
        run: dialyzer --build_plt --apps erts kernel stdlib

      - name: Static Code Analysis
        run: dialyzer --src -r src/
  
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: _build/
