name: Push to History Repository

on: 
  push:
    # tags:
      # - 'v*' # Matches version tags like v1.0, v2.0
    branches:
      - main  # Script is triggered whenever there is a push to the main branch

jobs:
  push-to-mileston:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to History Repository
        env:
          PAT: ${{ secrets.HISTORY_REPO_PAT }}
        run: |
          git remote add history https://github.com/palangdan-joanalyn/trial-history.git
          # git push milestone --tags
          git push history main:milestone