name: Push to History Repository

on: 
  push:
    # tags:
      # - 'v*' # Matches version tags like v1.0, v2.0
    branches:
      - main  # Script is triggered whenever there is a push to the main branch

jobs:
  push-to-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to History Repository
        env:
          GITHUB_TOKEN: ${{ secrets.HISTORY_REPO_PAT }}
        run: |
          git remote add history https://x-access-token:${{ secrets.HISTORY_PAT }}@github.com/palangdan-joanalyn/trial-history.git
          # git push milestone --tags
          git push history main:main