name: Push to History Repository

on: 
  push:
    branches:
      - main  # Script is triggered whenever there is a push to the main branch

jobs:
  push-to-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to History Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Check history repository"
          git remote add history https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/palangdan-joanalyn/trial-history.git
          git fetch history
          git status
          git pull history main --allow-unrelated-histories
          git push history main:main